name = Work Department simple layout
description = Special for WD
preview = preview.png
template = wd-home

; Regions
regions[branding]       = Branding
regions[help]           = Help
regions[pre_content]    = Pre-Content
regions[content]        = Content
regions[post_content]   = Post-Content
regions[sidebar_first]  = Sidebar
regions[actions]        = Actions
regions[footer]         = Footer
regions[footer_bottom]  = Footer Bottom

; Stylesheets
stylesheets[all][] = css/layouts/wd-home/wd-home.layout.css
